version: '3.8'

services:
  app_prod:
    build:
      context: .
      dockerfile: dockerfile.prod
      # STAGE utilizará por padrão a variável ${STAGE:-build-stage} conforme definido em dockerfile.prod
      # Será sobrescrita quando invocado explicitamente, por exemplo: STAGE=production docker compose -f docker-compose.prod.yaml up
      target: ${STAGE:-build-stage} 
    ports:
      - 3000:3000
    volumes:
      - .:/home/node/app
      - /home/node/app/public/js
      - /home/node/app/node_modules
    depends_on:
      - db_prod
      
  db_prod:
    image: mongo:6.0.3
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=root
